[package]
name = "hmcrovator"
version = "0.1.0"
authors = ["MartinVrbovcan <43181691+MartinVrbovcan@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
